services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx1024m"
      - OPENSEARCH_INITIAL_MB=512
      - OPENSEARCH_MAX_MB=1024
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 1536M

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"

  gateway_api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: gateway_api
    volumes:
      - .:/app
    environment:
      - PROFILING_ENABLED=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENSEARCH_URL=http://opensearch:9200
      - REDIS_URL=redis://redis:6379/0
      - INFERENCE_URL=http://inference_service:8001
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - "8000:8000"
    depends_on:
      - opensearch
      - redis
      - inference_service

  inference_service:
    build:
      context: .
      dockerfile: ./src/inference/Dockerfile
    container_name: inference_service
    volumes:
      - .:/app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - "8001:8001"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2048M

  celery_worker:
    build:
      context: .
      dockerfile: ./src/worker/Dockerfile
    container_name: celery_worker
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - OPENSEARCH_URL=http://opensearch:9200
    depends_on:
      - redis
      - opensearch

  frontend:
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    container_name: frontend
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://gateway_api:8000
    depends_on:
      - gateway_api
