"""Unit tests for Celery agent workflows."""

import json
from typing import Any
from unittest.mock import MagicMock, patch

import httpx
import respx
from celery.exceptions import Retry

from src.worker.agent_workflows import DLQTask, synthesize_agent_response


@respx.mock
@patch("src.worker.tools.search.redis.Redis.from_url")
@patch("src.worker.agent_workflows.completion")
def test_synthesize_with_candidates(mock_completion: MagicMock, mock_redis: MagicMock) -> None:
    """Test synthesis builds context and calls LLM."""
    mock_redis_client = MagicMock()
    mock_redis_client.get = MagicMock(return_value=None)
    mock_redis.return_value = mock_redis_client

    # Mock the external search API
    respx.post("https://api.tavily.com/search").mock(
        return_value=httpx.Response(200, json={"results": [{"url": "http://acme.com", "content": "Funding news"}]})
    )

    mock_msg = MagicMock()
    # Mock structured JSON response
    mock_msg.content = json.dumps({
        "summary": "Summary of Acme Corp findings.",
        "leads": [
            {"name": "Acme Corp", "industry": "Software", "domain": "acme.com", "locality": "NY", "country": "US", "year_founded": 2020, "size_range": "10-50"}
        ]
    })
    mock_choice = MagicMock()
    mock_choice.message = mock_msg
    mock_completion.return_value = MagicMock(choices=[mock_choice])

    candidates: list[dict[str, Any]] = []
    result = synthesize_agent_response("find software companies", candidates)
    
    assert result["summary"] == "Summary of Acme Corp findings."
    assert len(result["leads"]) == 1
    assert result["leads"][0]["name"] == "Acme Corp"
    assert "id" in result["leads"][0] # Ensure UUID was autogenerated
    mock_completion.assert_called_once()


@respx.mock
@patch("src.worker.tools.search.redis.Redis.from_url")
@patch("src.worker.agent_workflows.completion")
@patch("src.worker.agent_workflows.synthesize_agent_response.retry")
def test_synthesize_handles_llm_error(mock_retry: MagicMock, mock_completion: MagicMock, mock_redis: MagicMock) -> None:
    """Test synthesis triggers retry gracefully upon LLM failure."""
    mock_redis_client = MagicMock()
    mock_redis_client.get = MagicMock(return_value=None)
    mock_redis.return_value = mock_redis_client

    respx.post("https://api.tavily.com/search").mock(
        return_value=httpx.Response(200, json={"results": [{"url": "http://acme.com", "content": "Funding news"}]})
    )

    mock_completion.side_effect = Exception("LLM timeout")
    
    # We mock self.retry so that we don't depend on Celery's sync-mode exception behavior
    mock_retry.side_effect = Retry("Simulated retry")
    
    candidates: list[dict[str, Any]] = []
    
    try:
        synthesize_agent_response("test", candidates)
        assert False, "Should have raised Retry"
    except Retry:
        assert mock_completion.call_count == 1
        mock_retry.assert_called_once()


@patch("src.worker.agent_workflows.redis.Redis.from_url")
def test_dlq_task_on_failure(mock_redis: MagicMock) -> None:
    """Test the native DLQ Task pushes payloads dynamically."""
    mock_client = MagicMock()
    mock_redis.return_value = mock_client
    
    task = DLQTask()
    task.name = "test_bound"
    exc = Exception("Catastrophic error")
    
    mock_einfo = MagicMock()
    mock_einfo.traceback = "Traceback details..."
    
    task.on_failure(exc, "task-123", ("arg1",), {"kw": "val"}, mock_einfo)
    
    mock_client.lpush.assert_called_once()
    args, _ = mock_client.lpush.call_args
    assert args[0] == "celery:dlq"
    payload = json.loads(args[1])
    
    assert payload["task_id"] == "task-123"
    assert payload["exception"] == "Catastrophic error"
    assert payload["args"] == ["arg1"]


@respx.mock
@patch("src.worker.tools.search.redis.Redis.from_url")
@patch("src.worker.agent_workflows.completion")
@patch("src.worker.agent_workflows.synthesize_agent_response.retry")
def test_synthesize_handles_none_content(mock_retry: MagicMock, mock_completion: MagicMock, mock_redis: MagicMock) -> None:
    """Test synthesis handles None LLM content."""
    mock_redis_client = MagicMock()
    mock_redis_client.get = MagicMock(return_value=None)
    mock_redis.return_value = mock_redis_client

    respx.post("https://api.tavily.com/search").mock(
        return_value=httpx.Response(200, json={"results": []})
    )

    mock_msg = MagicMock()
    # Note: Litellm always returns string or None. If it's none, our updated try/except catches json parse failure and Retries!
    mock_msg.content = None
    mock_choice = MagicMock()
    mock_choice.message = mock_msg
    mock_completion.return_value = MagicMock(choices=[mock_choice])

    mock_retry.side_effect = Retry("Simulated retry on validation error")

    candidates: list[dict[str, Any]] = []
    try:
        synthesize_agent_response("test", candidates)
        assert False, "Should have raised Retry"
    except Retry:
        assert mock_completion.call_count == 1
        mock_retry.assert_called_once()
