"""Worker background tasks mapping agent workflows natively."""

import asyncio
import json
import logging
import os
import uuid
from typing import Any, Dict, List, Optional

import redis
from celery import Celery, Task
from litellm import completion
from pydantic import BaseModel

from src.worker.tools.search import fetch_recent_company_news

logger = logging.getLogger("worker")

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

celery_app = Celery("agent_workflows", broker=REDIS_URL, backend=REDIS_URL)


class DLQTask(Task):  # type: ignore[misc]
    """Custom celery task that triggers native Redis DLQ on failure."""

    def on_failure(
        self, exc: Exception, task_id: str, args: tuple[Any, ...], kwargs: dict[str, Any], einfo: Any
    ) -> None:
        """Route failed parameters to the native Redis DLQ namespace."""
        try:
            r = redis.Redis.from_url(REDIS_URL, decode_responses=True)
            payload = {
                "task_id": task_id,
                "task_name": self.name,
                "args": args,
                "kwargs": kwargs,
                "exception": str(exc),
                "traceback": str(einfo.traceback) if einfo else None,
            }
            r.lpush("celery:dlq", json.dumps(payload))
            logger.error(f"Task {task_id} failed permanently. Routed inputs to celery:dlq.")
        except Exception as dlq_err:
            logger.error(f"Failed to route task {task_id} to DLQ: {dlq_err}")

        super().on_failure(exc, task_id, args, kwargs, einfo)


class Lead(BaseModel):
    """A generated company profile lead strictly bound."""

    name: str
    industry: str
    domain: Optional[str] = None
    locality: str = ""
    country: str = ""
    year_founded: Optional[int] = None
    size_range: str = "Unknown"


class AgenticLeadsResponse(BaseModel):
    """Pydantic schema mapping structured output for Celery pipeline."""

    summary: str
    leads: List[Lead]


# Celery's task decorator lacks proper type hints
@celery_app.task(bind=True, base=DLQTask, max_retries=3, name="tasks.agent_workflows.synthesize_agent_response")  # type: ignore[untyped-decorator]
def synthesize_agent_response(self: Any, query: str, candidates: list[Dict[str, Any]]) -> Dict[str, Any]:
    """Coordinates nested search synthesis natively executing external searches unconditionally."""

    # fetch external news payload natively based entirely on the query
    async def fetch_news(search_query: str) -> str:
        # Evaluate tools explicitly
        return await fetch_recent_company_news(search_query)  # type: ignore[no-any-return]

    try:
        context = asyncio.run(fetch_news(query))
    except Exception as e:
        logger.error(f"External search failed: {e}")
        context = "External search temporarily unavailable."

    prompt = (
        f"Context provided by external search:\n{context}\n\n"
        f"User Query: {query}\n\n"
        "You are an Information Retrieval expert. Using ONLY the provided context above, extract the companies mentioned: "  # noqa: E501
        "as fully complete 'leads'. "
        "CRITICAL GUARDRAIL: Only extract companies that are EXPLICITLY referenced in the context. "
        "Do NOT invent details, hallucinate names, or mention companies not in the context. "
        "For each lead, extract their name, industry, domain, location, founding year, and size. "
        "If a specific detail is missing, leave it blank or 'Unknown'. "
        "Finally, write a brief 'summary' synthesizing the overall findings, including citations and URLs mentioned in the context."  # noqa: E501
    )

    try:
        response = completion(
            model="gemini/gemini-3.1-flash-lite-preview",
            messages=[
                {
                    "role": "system",
                    "content": "You are a helpful B2B structured data extraction assistant.",
                },
                {"role": "user", "content": prompt},
            ],
            response_format=AgenticLeadsResponse,
        )

        # Parse Pydantic response securely
        parsed = AgenticLeadsResponse.model_validate_json(response.choices[0].message.content)

        # Mutate leads to ensure UUID integrity bridging downstream systems cleanly, preventing hallucinated keys
        leads_payload = []
        for lead in parsed.leads:
            lead_dict = lead.model_dump()
            lead_dict["id"] = uuid.uuid4().hex  # Secure autogenerated universally unique ID
            leads_payload.append(lead_dict)

        return {"summary": parsed.summary, "raw_markdown": context, "leads": leads_payload}

    except Exception as e:
        logger.error(f"Agent synthesis failed or hallucinated unparsable constraints: {e}")
        raise self.retry(exc=e, countdown=1)
