apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
  clusterIP: None
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.11.0
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: OPENSEARCH_INITIAL_MB
              value: "512"
            - name: OPENSEARCH_MAX_MB
              value: "512"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9300
              name: inter-node
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          hostPath:
            path: /mnt/data/opensearch
            type: DirectoryOrCreate
